name: "Manual - Shell Script Linter"
on:
  workflow_dispatch:
      inputs:
        path:
          description: "Path to the shell scripts to lint"
          required: true
          default: "src/**/*.sh"
        severity:
          description: "Minimum Severity (style, info, warning, error)"
          required: true
          default: "style"

jobs:
  shellchecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Shell Linter
      uses: azohra/shell-linter@v0.6.0
      with:
        path: ${{ github.event.inputs.path }}
        severity: ${{ github.event.inputs.severity }}
      env:
        SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison