name: "Release dev container features (v2)"
on:
  push:
    tags:
      - "v0.0.2" # Temporary
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate tgz
        uses: ./.github/devcontainers-action # devcontainers/action
        with:
          publish-features: "true"
          base-path-to-features: "./src"

      - name: Get or Create Release at current tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Lets us upload our own artifact from previous step
          artifactErrorsFailBuild: true
          artifacts: "./*.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
