name: "Test Features (manual)"
on: 
  workflow_dispatch:
    inputs:
      features:
        description: 'list of features to execute tests against'     
        required: true
        default: 'go dotnet'
      baseImage: 
        description: 'Base image'     
        required: true
        default: 'ubuntu:focal'
      logLevel:
        description: 'Log Level (info/debug/trace)'
        default: 'info'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: " Testing '${{ github.event.inputs.features }}' against '${{ github.event.inputs.baseImage }}'"
        run: npx --yes ./devcontainers-cli-0.3.0.tgz features test --features ${{ github.event.inputs.features }} --base-image ${{ github.event.inputs.baseImage }} --collection-folder `pwd` --log-level ${{ github.event.inputs.logLevel }} 
